### ISSUE TITLE
init build fails

### ISSUE THREAD

**Issue by coreybruce** [zeldaret/mm#1239]
Hey I was trying to build this on my Raspberry pi 4 but I ran into a issue

Log:
https://gist.github.com/coreybruce/c3d9916c43bfa0124be599a02a53b9d5

**Comment by hensldm** [comment]
Since it looks like the `fixbaserom.py` tool is complaining about not finding the baserom YAZ0 compressed, it suggests an incorrect rom was used. The md5sum of your rom should match what is mentioned in the README. The updated `fixbaserom.py` in #1240 should spit out a better error if this is the case.

**Comment by coreybruce** [comment]
> Since it looks like the `fixbaserom.py` tool is complaining about not finding the baserom YAZ0 compressed, it suggests an incorrect rom was used. The md5sum of your rom should match what is mentioned in the README. The updated `fixbaserom.py` in #1240 should spit out a better error if this is the case.

Oh I see, does the rom have to be the US rom for example?

**Comment by engineer124** [comment]
> Oh I see, does the rom have to be the US rom for example?

Yes, we are currently decompiling version US 1.0

**Comment by coreybruce** [comment]
Ah ok I See, so is this project a recompilation project like zelda3 that allows you to play on PC or just a rom de-compilation?

**Comment by engineer124** [comment]
You can find more information about the project here: https://zelda64.dev/games/mm
The purpose is to recreate the original rom byte-for-byte. What you get out is precisely the rom you get in.

**Comment by engineer124** [comment]
Closing this as the issue was identified to be an incorrect rom
