### ISSUE TITLE
Reduce compile time warnings.

### ISSUE THREAD

**Issue by Kenix3** [zeldaret/mm#147]
We should fix up the code to remove as many compiler warnings as possible while still keeping OK.

Further, we should implement something like this PR for OOT until we are ready to elevate warnings to errors.
https://github.com/zeldaret/oot/pull/768

**Comment by EllipticEllipsis** [comment]
I think we should perhaps be a little less stringent than this: in OoT there are several pretty horrible coding mistakes that cause warnings, that it would be possible to fix while maintaining OK, but OoT prefers not to since they are genuine mistakes in the original, not our own.

**Comment by Kenix3** [comment]
> 
> 
> I think we should perhaps be a little less stringent than this: in OoT there are several pretty horrible coding mistakes that cause warnings, that it would be possible to fix while maintaining OK, but OoT prefers not to since they are genuine mistakes in the original, not our own.

These would probably not be OK? Either way, if it's OK, how can you prove the original code had the mistake?

For MM I would rather fix the defect, as long as it's OK.

**Comment by Kenix3** [comment]
https://github.com/zeldaret/mm/pull/152
