### ISSUE TITLE
ZAPD, asm-processor, asm-differ, decomp-permuter, and any other tools that have their own repo should be made into a subrepo.

### ISSUE THREAD

**Issue by Kenix3** [zeldaret/mm#153]
We will no longer be using submodules.
We also want to move tools that are used as part of building to a separate folder in the tools folder.
We need a specific directory for tools that are meant to be run manually on the command line.
We also want to ensure that there is a good reason for a tool in the root directory of the project.

**Comment by AngheloAlf** [comment]
I think everything in this issue has been done already, or am I missing something?

**Comment by AngheloAlf** [comment]
Everything is now a subrepo. I'll close this issue.
