### ISSUE TITLE
Rebase and Force-push

### ISSUE THREAD

**Issue by ReNardier** [zeldaret/mm#791]
hi, been a lurker of this project for a while, and i have noticed that "Please don't rebase and force-push: it makes it harder to review since GitHub loses all the comments and it's hard to see what's actually changed." or something along those lines as had to be say more than once(here and on the ocarina), wouldn't it be appropriate then to add this warning on the "Contributing" section of README.md?

**Comment by EllipticEllipsis** [comment]
Thank you for the suggestion, we have intended to incorporate this into the contributing documentation for a while now, and the PR that was just opened does so.
